live_config_reload: true

dpi:
  x: 120.0
  y: 120.0

window:
  startup_mode: Maximized

font:
  normal:
    family: Operator Mono
    style: Medium
  bold:
    style: Bold
  italic:
    style: Italic
  size: 15.0

  use_thin_strokes: false

bell:
  duration: 0

import:
  - ~/.config/alacritty/dracula.yml
