require('settings')
require('setup')
require('plugs')
require('telescope')
require('NERDTree')
require('undo')
require('highlight')
require('clipboard')
require('color-column')
require('newline-comment')
require('lsp')
--require('nvim-treesitter')

