require('settings')
require('setup')
require('plugs')
require('NERDTree')
require('undo')
require('highlight')
require('clipboard')
require('color-column')
require('newline-comment')
require('lsp')
require('telescope-setup')
-- require('nvim-treesitter-setup')

