brew "uptech/oss/alt"
brew "apktool"
brew "awscli"
brew "bash"
brew "bat"
brew "bazelbuild/tap/bazel"
brew "blender/tap/rome"
brew "carthage"
brew "chisel"
brew "chruby"
brew "colordiff"
brew "coreutils"
brew "ctags"
brew "dduan/formulae/drstring"
brew "dduan/homebrew-formulae/tre" #dduan/formulae
brew "diff-so-fancy"
brew "dust" # Better du -sh
brew "drone"
brew "exa" # Better ls
brew "fd" # Better find
brew "fish"
brew "fzf"
brew "ghi"
brew "git"
brew "git-extras"
brew "git-lfs"
brew "gnu-sed"
brew "gource"
brew "graphviz"
brew "heroku/brew/heroku"
brew "hexyl" # Pretty hex viewer
brew "hub"
brew "hyperfine" # Command line perf
brew "isacikgoz/gitin/gitin"
brew "jfrog-cli-go"
brew "keith/formulae/tag" # keith/formula
brew "mdcat" # Terminal Markdown rendering
brew "mint"
brew "mitmproxy"
brew "neovim"
brew "node"
brew "python"
brew "rbenv"
brew "scmpuff"
brew "swiftlint"
brew "tgt/brewhouse/tapctl"
brew "the_silver_searcher"
brew "tig"
brew "vim"
brew "watchexec" # Watch directory, perform action
brew "wget"
brew "zsh"
brew "z" # Smart directory browsing
cask "1password-cli"
cask "bartender"
cask "bettertouchtool"
cask "java"
cask "periphery"
cask "provisionql"
cask "quitter"
cask "tripmode"
tap "bazelbuild/tap", pin: true
tap "blender/tap"
tap "dduan/homebrew-formulae"
tap "drone/drone"
tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "isacikgoz/gitin"
tap "keith/formulae"
tap "peripheryapp/periphery"
tap "tgt/brewhouse", "git@git.target.com:brew/house.git"
