import = ["/Users/ekerber/.config/alacritty/dracula.toml"]
live_config_reload = true

[bell]
duration = 0

[font]
size = 14.0

[font.bold]
style = "Bold"

[font.italic]
style = "Italic"

[font.normal]
family = "OperatorMono Nerd Font"
style = "Medium"

[[keyboard.bindings]]
chars = "\u0002%"
key = "D"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002\""
key = "D"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0002c"
key = "T"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002x"
key = "W"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002\u001B[D"
key = "LBracket"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002\u001B[C"
key = "RBracket"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002p"
key = "LBracket"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0002n"
key = "RBracket"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u00021"
key = "Key1"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00022"
key = "Key2"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00023"
key = "Key3"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00024"
key = "Key4"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00025"
key = "Key5"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00026"
key = "Key6"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00027"
key = "Key7"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00028"
key = "Key8"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00029"
key = "Key9"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002H"
key = "Left"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002J"
key = "Down"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002K"
key = "Up"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002L"
key = "Right"
mods = "Command"

[scrolling]
history = 10000
multiplier = 3

[window]
startup_mode = "Maximized"
